"""Metadonnees des 15 pays CEDEAO couverts par BebeCare."""

PAYS = {
    "bj": {"nom": "Bénin", "nom_en": "Benin", "iso2": "BJ", "iso3": "BEN",
           "drapeau": "🇧🇯", "langue": "fr", "urgence": "112",
           "capitale": "Cotonou", "lat": 6.37, "lon": 2.42, "zoom": 7},
    "bf": {"nom": "Burkina Faso", "nom_en": "Burkina Faso", "iso2": "BF", "iso3": "BFA",
           "drapeau": "🇧🇫", "langue": "fr", "urgence": "112",
           "capitale": "Ouagadougou", "lat": 12.37, "lon": -1.53, "zoom": 6},
    "cv": {"nom": "Cabo Verde", "nom_en": "Cabo Verde", "iso2": "CV", "iso3": "CPV",
           "drapeau": "🇨🇻", "langue": "pt", "urgence": "130",
           "capitale": "Praia", "lat": 14.93, "lon": -23.51, "zoom": 8},
    "ci": {"nom": "Côte d'Ivoire", "nom_en": "Ivory Coast", "iso2": "CI", "iso3": "CIV",
           "drapeau": "🇨🇮", "langue": "fr", "urgence": "185",
           "capitale": "Abidjan", "lat": 5.35, "lon": -4.03, "zoom": 7},
    "gm": {"nom": "Gambie", "nom_en": "Gambia", "iso2": "GM", "iso3": "GMB",
           "drapeau": "🇬🇲", "langue": "en", "urgence": "116",
           "capitale": "Banjul", "lat": 13.45, "lon": -16.58, "zoom": 8},
    "gh": {"nom": "Ghana", "nom_en": "Ghana", "iso2": "GH", "iso3": "GHA",
           "drapeau": "🇬🇭", "langue": "en", "urgence": "193",
           "capitale": "Accra", "lat": 5.60, "lon": -0.19, "zoom": 7},
    "gn": {"nom": "Guinée", "nom_en": "Guinea", "iso2": "GN", "iso3": "GIN",
           "drapeau": "🇬🇳", "langue": "fr", "urgence": "442",
           "capitale": "Conakry", "lat": 9.51, "lon": -13.71, "zoom": 7},
    "gw": {"nom": "Guinée-Bissau", "nom_en": "Guinea-Bissau", "iso2": "GW", "iso3": "GNB",
           "drapeau": "🇬🇼", "langue": "pt", "urgence": "119",
           "capitale": "Bissau", "lat": 11.86, "lon": -15.60, "zoom": 8},
    "lr": {"nom": "Liberia", "nom_en": "Liberia", "iso2": "LR", "iso3": "LBR",
           "drapeau": "🇱🇷", "langue": "en", "urgence": "911",
           "capitale": "Monrovia", "lat": 6.30, "lon": -10.80, "zoom": 7},
    "ml": {"nom": "Mali", "nom_en": "Mali", "iso2": "ML", "iso3": "MLI",
           "drapeau": "🇲🇱", "langue": "fr", "urgence": "15",
           "capitale": "Bamako", "lat": 12.64, "lon": -8.00, "zoom": 6},
    "ne": {"nom": "Niger", "nom_en": "Niger", "iso2": "NE", "iso3": "NER",
           "drapeau": "🇳🇪", "langue": "fr", "urgence": "15",
           "capitale": "Niamey", "lat": 13.51, "lon": 2.12, "zoom": 6},
    "ng": {"nom": "Nigéria", "nom_en": "Nigeria", "iso2": "NG", "iso3": "NGA",
           "drapeau": "🇳🇬", "langue": "en", "urgence": "112",
           "capitale": "Abuja", "lat": 9.06, "lon": 7.49, "zoom": 6},
    "sn": {"nom": "Sénégal", "nom_en": "Senegal", "iso2": "SN", "iso3": "SEN",
           "drapeau": "🇸🇳", "langue": "fr", "urgence": "1515",
           "capitale": "Dakar", "lat": 14.72, "lon": -17.47, "zoom": 7},
    "sl": {"nom": "Sierra Leone", "nom_en": "Sierra Leone", "iso2": "SL", "iso3": "SLE",
           "drapeau": "🇸🇱", "langue": "en", "urgence": "999",
           "capitale": "Freetown", "lat": 8.48, "lon": -13.23, "zoom": 8},
    "tg": {"nom": "Togo", "nom_en": "Togo", "iso2": "TG", "iso3": "TGO",
           "drapeau": "🇹🇬", "langue": "fr", "urgence": "8200",
           "capitale": "Lomé", "lat": 6.13, "lon": 1.22, "zoom": 7},
}

# Pays dont le SNIS national tourne sur DHIS2 (source : dhis2.org/in-action)
DHIS2_NATIONAL = {"bj", "bf", "ci", "gh", "gn", "gw", "lr", "ml", "ne",
                  "ng", "sn", "sl", "tg", "gm"}

CATEGORIES = {
    "hopital": {"fr": "Hôpital", "en": "Hospital", "couleur": "#d7263d", "icone": "🏥"},
    "centre_sante": {"fr": "Centre de santé", "en": "Health centre", "couleur": "#1b998b", "icone": "➕"},
    "maternite": {"fr": "Maternité", "en": "Maternity", "couleur": "#c04ac0", "icone": "🤰"},
    "pharmacie": {"fr": "Pharmacie", "en": "Pharmacy", "couleur": "#2e86ab", "icone": "💊"},
    "medecin": {"fr": "Médecin", "en": "Doctor", "couleur": "#f4a259", "icone": "🩺"},
    "laboratoire": {"fr": "Laboratoire", "en": "Laboratory", "couleur": "#7b6d8d", "icone": "🔬"},
    "sante_autre": {"fr": "Autre structure", "en": "Other facility", "couleur": "#8a8a8a", "icone": "⚕️"},
}
