"""Generation du calendrier vaccinal personnalise en PDF.

Pourquoi un PDF plutot qu'un .ics ?
  Les rappels agenda (.ics) ne s'ouvrent pas sur beaucoup de telephones
  Android d'entree de gamme, tres repandus chez les families visees. Un PDF,
  lui, s'ouvre partout, s'imprime au centre de sante et se partage sur
  WhatsApp, canal dominant en Afrique de l'Ouest.

Le module utilise fpdf2 (pur Python, aucune dependance systeme) et les
polices de base en cp1252 : tous les accents francais passent, les
caracteres exotiques sont remplaces proprement.
"""
from __future__ import annotations

from fpdf import FPDF

TEAL = (0, 105, 92)
ENCRE = (15, 43, 39)
GRIS = (91, 122, 117)

COULEURS_ETAT = {
    "fait":    {"fond": (231, 246, 236), "texte": (30, 123, 52)},
    "retard":  {"fond": (253, 234, 234), "texte": (183, 28, 28)},
    "bientot": {"fond": (255, 243, 224), "texte": (138, 90, 0)},
    "futur":   {"fond": (240, 248, 247), "texte": GRIS},
}

TXT = {
    "fr": {
        "titre": "BébéCare",
        "sous_titre": "Calendrier vaccinal personnalisé",
        "enfant": "Enfant",
        "sans_nom": "(prénom non renseigné)",
        "ne_le": "Né(e) le",
        "calendrier_de": "Calendrier officiel PEV",
        "age_aujourdhui": "Âge aujourd'hui",
        "mois": "mois",
        "doses_faites": "doses faites",
        "en_retard": "en retard",
        "bientot": "dans le mois",
        "col_vaccin": "Vaccin",
        "col_dose": "Dose",
        "col_age": "Âge prévu",
        "col_date": "Date prévue",
        "col_statut": "Statut",
        "e_fait": "FAIT",
        "e_retard": "EN RETARD",
        "e_bientot": "BIENTÔT",
        "e_futur": "À VENIR",
        "pied_1": "Apportez ce document ET le carnet de santé de l'enfant à chaque rendez-vous.",
        "pied_2": "Les vaccins du PEV sont gratuits dans les centres de santé publics.",
        "pied_3": "Document d'information généré par BébéCare : il ne remplace ni le carnet officiel, ni un avis médical.",
        "source": "Source",
        "genere_le": "Généré le",
    },
    "en": {
        "titre": "BébéCare",
        "sous_titre": "Personalised vaccination calendar",
        "enfant": "Child",
        "sans_nom": "(name not provided)",
        "ne_le": "Born on",
        "calendrier_de": "Official EPI schedule",
        "age_aujourdhui": "Age today",
        "mois": "months",
        "doses_faites": "doses done",
        "en_retard": "overdue",
        "bientot": "due this month",
        "col_vaccin": "Vaccine",
        "col_dose": "Dose",
        "col_age": "Due age",
        "col_date": "Due date",
        "col_statut": "Status",
        "e_fait": "DONE",
        "e_retard": "OVERDUE",
        "e_bientot": "DUE SOON",
        "e_futur": "UPCOMING",
        "pied_1": "Bring this document AND the child's health card to every visit.",
        "pied_2": "EPI vaccines are free in public health centres.",
        "pied_3": "Information document generated by BébéCare: it replaces neither the official card nor medical advice.",
        "source": "Source",
        "genere_le": "Generated on",
    },
}


def _safe(txt) -> str:
    """Les polices de base codent en cp1252 : tout le reste est remplace."""
    return str(txt).encode("cp1252", "replace").decode("cp1252")


def _tronquer(txt: str, n: int) -> str:
    txt = _safe(txt)
    return txt if len(txt) <= n else txt[: n - 1] + "…"  # … existe en cp1252


def _date_lisible(iso: str, langue: str) -> str:
    """2025-03-14 -> 14/03/2025 (format court, lisible partout)."""
    try:
        a, m, j = iso[:10].split("-")
        return f"{j}/{m}/{a}"
    except Exception:
        return iso


class _Pdf(FPDF):
    def header(self):
        # Bandeau teal pleine largeur
        self.set_fill_color(*TEAL)
        self.rect(0, 0, 210, 24, "F")

    def footer(self):
        self.set_y(-12)
        self.set_font("helvetica", "I", 7.5)
        self.set_text_color(*GRIS)
        self.cell(0, 5, _safe(self.pied_page), align="C")


def generer(pays_nom: str, planning: dict, prenom: str,
            langue: str = "fr") -> bytes:
    """Rend le PDF du planning vaccinal personnalise. Renvoie des octets."""
    L = TXT["en" if langue == "en" else "fr"]
    resume = planning["resume"]

    pdf = _Pdf("P", "mm", "A4")
    pdf.set_margins(10, 10, 10)
    pdf.set_auto_page_break(True, 16)
    pdf.pied_page = (f"BébéCare : {L['pied_3']}")
    pdf.add_page()

    # -- Bandeau ---------------------------------------------------------
    pdf.set_xy(10, 5)
    pdf.set_font("helvetica", "B", 17)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, L["titre"])
    pdf.set_xy(10, 13.5)
    pdf.set_font("helvetica", "", 10.5)
    pdf.cell(0, 6, _safe(f"{L['sous_titre']} : {pays_nom}"))

    # -- Bloc enfant ------------------------------------------------------
    pdf.set_y(30)
    pdf.set_text_color(*ENCRE)
    pdf.set_font("helvetica", "B", 12)
    nom = _safe(prenom.strip()) if prenom and prenom.strip() else L["sans_nom"]
    pdf.cell(0, 7, f"{L['enfant']} : {nom}")
    pdf.ln(7)
    pdf.set_font("helvetica", "", 10.5)
    pdf.set_text_color(*GRIS)
    pdf.cell(0, 6, _safe(
        f"{L['ne_le']} : {_date_lisible(planning['date_naissance'], langue)}"
        f"   |   {L['age_aujourdhui']} : {planning['age_mois']} {L['mois']}"
        f"   |   {L['calendrier_de']} : {pays_nom}"))
    pdf.ln(9)

    # -- Resume en pastilles colorees ------------------------------------
    pdf.set_font("helvetica", "B", 10)
    pastilles = [
        (f"{resume['faits']}/{resume['total']} {L['doses_faites']}", COULEURS_ETAT["fait"]),
        (f"{resume['en_retard']} {L['en_retard']}",
         COULEURS_ETAT["retard"] if resume["en_retard"] else COULEURS_ETAT["fait"]),
        (f"{resume['dans_le_mois']} {L['bientot']}", COULEURS_ETAT["bientot"]),
    ]
    x = 10
    for texte, style in pastilles:
        texte = _safe(texte)
        w = pdf.get_string_width(texte) + 10
        pdf.set_fill_color(*style["fond"])
        pdf.set_text_color(*style["texte"])
        pdf.set_xy(x, pdf.get_y())
        pdf.cell(w, 8, texte, border=0, fill=True, align="C")
        x += w + 4
    pdf.ln(14)

    # -- Tableau -----------------------------------------------------------
    entetes = [L["col_vaccin"], L["col_dose"], L["col_age"], L["col_date"], L["col_statut"]]
    larges = [78, 15, 28, 29, 40]

    pdf.set_font("helvetica", "B", 9.5)
    pdf.set_fill_color(224, 242, 241)   # teal-100
    pdf.set_text_color(*TEAL)
    for h, w in zip(entetes, larges):
        pdf.cell(w, 8, _safe(h), border=0, fill=True)
    pdf.ln(8)

    etat_txt = {"fait": L["e_fait"], "retard": L["e_retard"],
                "bientot": L["e_bientot"], "futur": L["e_futur"]}
    pdf.set_font("helvetica", "", 9.5)
    for i, e in enumerate(planning["etapes"]):
        style = COULEURS_ETAT[e["etat"]]
        y0 = pdf.get_y()
        if y0 > 268:        # saut de page propre avant une nouvelle ligne
            pdf.add_page()
            pdf.set_font("helvetica", "B", 9.5)
            pdf.set_fill_color(224, 242, 241)
            pdf.set_text_color(*TEAL)
            for h, w in zip(entetes, larges):
                pdf.cell(w, 8, _safe(h), border=0, fill=True)
            pdf.ln(8)
            pdf.set_font("helvetica", "", 9.5)

        rempl = i % 2 == 0
        pdf.set_fill_color(246, 251, 250)
        pdf.set_text_color(*ENCRE)
        pdf.set_font("helvetica", "B" if e["etat"] == "retard" else "", 9.5)
        vaccin = _tronquer(e["vaccin"], 44)
        pdf.cell(larges[0], 7.5, vaccin, border=0, fill=rempl)
        pdf.set_font("helvetica", "", 9.5)
        pdf.cell(larges[1], 7.5, str(e["dose"]), border=0, fill=rempl, align="C")
        pdf.set_text_color(*GRIS)
        pdf.cell(larges[2], 7.5, _tronquer(e["age"], 16), border=0, fill=rempl)
        pdf.set_text_color(*ENCRE)
        pdf.cell(larges[3], 7.5, _date_lisible(e["date_prevue"], langue), border=0, fill=rempl)
        # pastille statut
        pdf.set_fill_color(*style["fond"])
        pdf.set_text_color(*style["texte"])
        pdf.set_font("helvetica", "B", 8)
        pdf.cell(larges[4], 7.5, _safe(etat_txt[e["etat"]]), border=0, fill=True, align="C")
        pdf.set_font("helvetica", "", 9.5)
        pdf.ln(7.5)

    # -- Pied informatif ----------------------------------------------------
    pdf.ln(5)
    pdf.set_x(pdf.l_margin)
    pdf.set_text_color(*GRIS)
    pdf.set_font("helvetica", "", 9)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _safe(f"{L['pied_1']} {L['pied_2']}"))
    pdf.set_x(pdf.l_margin)
    pdf.set_font("helvetica", "I", 8)
    pdf.multi_cell(0, 4.5, _safe(
        f"{L['source']} : {planning.get('source', 'OMS')}   |   "
        f"{L['genere_le']} : {planning.get('genere_le', '')}"))

    return bytes(pdf.output())
